all:
  children:
    servers:
      children:
        ubuntu:
          hosts:
            ubuntu:
              ansible_host: 104.197.109.51 
        centos:
          hosts:
            centos:
              ansible_host: 34.67.73.229 