---
- name: Install nginx on Debian
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install nginx on RedHat
  ansible.builtin.dnf:
    name: nginx
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install certbot packages on Debian
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: true
  when:
    - certbot_enabled
    - ansible_facts['os_family'] == "Debian"

- name: Install nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Restart nginx


- name: Ensure nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Generate Let's Encrypt certificate and enable HTTPS with certbot
  ansible.builtin.command:
    cmd: >
      certbot --nginx
      --non-interactive
      --agree-tos
      --email {{ certbot_email }}
      -d {{ server_name }}
      {% if certbot_staging %}--staging{% endif %}
  args:
    creates: /etc/letsencrypt/live/{{ server_name }}/fullchain.pem
  when: certbot_enabled
  notify: Restart nginx
