---

- name: Create healthcheck directory
  ansible.builtin.file:
    path: /opt/healthcheck
    state: directory
    mode: "0755"

- name: Create healthcheck script
  ansible.builtin.copy:
    dest: /opt/healthcheck/check.sh
    mode: "0755"
    content: |
      #!/bin/bash

      echo -e "\n Total Disk Usage\n"
      df -h | awk '{print $1, $2, $4}' | column -t

      echo -e "\n Largest Directories\n"
      du -ah --max-depth=1 / 2>&1 | sort -hr | awk '!/du: cannot/ {print $0}'

      echo -e "\n Total Memory Usage\n"
      free -h | awk '{print $1, $2, $3}' | column -t

      echo -e "\n Nginx Status\n"
      systemctl is-active nginx

- name: Create healthcheck service
  ansible.builtin.copy:
    dest: /etc/systemd/system/healthcheck.service
    mode: "0644"
    content: |
      [Unit]
      Description=HealthCheck Service shows du df free

      [Service]
      Type=oneshot
      ExecStart=/opt/healthcheck/check.sh
      User=root

- name: Create healthcheck timer
  ansible.builtin.copy:
    dest: /etc/systemd/system/healthcheck.timer
    mode: "0644"
    content: |
      [Unit]
      Description=Run HealthCheck every 5 min

      [Timer]
      OnCalendar=*:0/5

      [Install]
      WantedBy=timers.target

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable and start healthcheck timer
  ansible.builtin.systemd_service:
    name: healthcheck.timer
    enabled: true
    state: started

- name: Check healthcheck timer status
  ansible.builtin.command:
    cmd: systemctl status healthcheck.timer
  register: week5_healthcheck_status
  changed_when: false

- name: Show healthcheck timer status
  ansible.builtin.debug:
    var: week5_healthcheck_status.stdout_lines
