---
- name: Set and manage logrotate
  ansible.builtin.copy:
    dest: /etc/logrotate.d/app_logs
    content: |
      /opt/app/logs/*.log {
          weekly
          rotate 4
          compress
          delaycompress
      }
    mode: "0644"
