---
- name: Create sysctl config file
  ansible.builtin.copy:
    dest: /etc/sysctl.d/lab2-custom.conf
    content: |
      net.ipv4.ip_forward = 1
      vm.swappiness = 10
      net.core.somaxconn = 65535
    mode: "0644"
  notify: Reload sysctl
