frontend:
  enabled: true
  replicaCount: 3
  image:
    repository: week6-frontend
    tag: "v1"
    pullPolicy: Never
  containerPort: 80

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      memory: 128Mi
      cpu: "0.5"
    requests:
      memory: 100Mi
      cpu: "0.5"
    
  livenessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
  
  readinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10



backend:
  enabled: true
  replicaCount: 2
  image:
    repository: week6-backend
    tag: "v1"
    pullPolicy: Never
  containerPort: 5000

  service:
    type: ClusterIP
    port: 5000

  resources:
    limits:
      memory: 256Mi
      cpu: "1.5"
    requests:
      memory: 128Mi
      cpu: "1.0"
    
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
  
  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50



postgresql:
  enabled: true
  replicaCount: 1
  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  containerPort: 5432

  service:
    type: ClusterIP
    port: 5432

  resources:
    limits:
      memory: 256Mi
      cpu: "1.5"
    requests:
      memory: 128Mi
      cpu: "1.0"
    
  readinessProbe:
    exec:
      command:
        - sh
        - -c
        - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
    initialDelaySeconds: 5
    periodSeconds: 10

  persistence:
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: ""



config:
  postgresDatabase: app
  postgresUser: postgres
  databasePort: "5432"
  


secrets:
  existingSecret: week6-secret



gateway:
  enabled: true
  className: cluster-gateway
  hostname: myapp.local
  tls:
    enabled: true
    existingSecret: myapp-tls



httpRedirect:
  enabled: true
  statusCode: 301



cronjob:
  enabled: true
  schedule: "*/5 * * * *"
  image:
    repository: curlimages/curl
    tag: "8.12.1"
    pullPolicy: IfNotPresent
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3



rbac:
  enabled: true
  serviceAccountName: app-reader



networkPolicy:
  enabled: true
  defaultDeny: true
  gatewayNamespace: envoy-gateway-system
  dnsNamespace: kube-system





