apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: lab-app
data:
  init.sql: |
    create table if not exists messages (id SERIAL PRIMARY KEY, message TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    insert into messages (message) values ('all done');