apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: lab-app
spec:
  serviceName: postgres-headless
  replicas: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: postgres

  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine

          envFrom:
            - configMapRef:
                name: week6-config
            - secretRef:
                name: week6-secret

          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          ports:
            - name: postgres
              containerPort: 5432

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi