apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-final.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-final.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: config

data:
  POSTGRES_DB: "{{ .Values.config.postgresDatabase }}"
  POSTGRES_USER: "{{ .Values.config.postgresUser }}"

  DB_HOST: "{{ include "k8s-final.fullname" . }}-postgresql"
  DB_PORT: "{{ .Values.config.databasePort }}"
  DB_NAME: "{{ .Values.config.postgresDatabase }}"
  DB_USER: "{{ .Values.config.postgresUser }}"