{{- if .Values.networkPolicy.enabled }}
{{- if .Values.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "k8s-final.fullname" . }}-allow-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-final.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: network-policy

spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8s-final.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: "{{ .Values.networkPolicy.gatewayNamespace }}"

      ports:
        - protocol: TCP
          port: {{ .Values.frontend.containerPort }}

  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "k8s-final.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: backend

      ports:
        - protocol: TCP
          port: {{ .Values.backend.containerPort }}
{{- end }}
{{- end }}