all:
  children:
    servers:
      children:
        ubuntu:
          hosts:
            ubuntu1:
              ansible_host: 104.197.109.51
            ubuntu2:
              ansible_host: 35.184.104.12 
        centos:
          hosts:
            centos:
              ansible_host: 34.67.73.229 