all:
  children:
    servers:
      children:
        ubuntu:
          hosts:
            manager1:
              ansible_host: 34.46.16.252
              internal_ip: 10.128.0.18
            worker1:
              ansible_host: 34.136.17.29
              internal_ip: 10.128.0.19
            worker2:
              ansible_host: 34.28.15.98
              internal_ip: 10.128.0.20
            worker3:
              ansible_host: 136.114.17.163
              internal_ip: 10.128.0.21
            worker4:
              ansible_host: 34.118.108.212
              internal_ip: 10.186.0.2
            worker5:
              ansible_host: 34.154.244.94
              internal_ip: 10.198.0.2
