---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-reader-binding
  namespace: lab-app
subjects:
  - kind: ServiceAccount
    name: app-reader
    namespace: lab-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-reader-role