all:
  children:
    staging:
      hosts:
        worker4:
          ansible_host: 34.118.108.212
          internal_ip: 10.186.0.2

    production:
      hosts:
        worker5:
          ansible_host: 34.154.244.94
          internal_ip: 10.198.0.2
