---
- name: Group add ops
  ansible.builtin.group:
    name: ops
    state: present

# https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/group_module.html#ansible-collections-ansible-builtin-group-module
- name: Group add developer
  ansible.builtin.group:
    name: developer
    state: present

- name: User dev1 # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/user_module.html
  ansible.builtin.user:
    name: dev1
    create_home: true
    groups:
      - developer

- name: User dev2
  ansible.builtin.user:
    name: dev2
    create_home: true
    groups:
      - developer

- name: User deployer
  ansible.builtin.user:
    name: deployer
    create_home: true
    groups:
      - ops
