---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: lab-app
  labels:
    app.kubernetes.io/name: &app nginx
    app.kubernetes.io/version: &version "1.27"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/version: *version
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *app
        app.kubernetes.io/version: *version
    spec:
      containers:
        - name: nginx
          image: week6-frontend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "0.5"
            requests:
              memory: "100Mi"
              cpu: "0.5"
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
